[package]
name = "cosmic-greeter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
env_logger = "0.10"
freedesktop_entry_parser = "1"
log = "0.4"
pam-client = "0.5"
pwd = "1"
shlex = "1"
wayland-client = "0.31"

[dependencies.cosmic-bg-config]
git = "https://github.com/pop-os/cosmic-bg"
branch = "master_jammy"

[dependencies.greetd_ipc]
version = "0.9"
features = ["sync-codec"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "wayland"]

[dependencies.tokio]
version = "1"
features = ["full"]
