[package]
name = "cosmic-greeter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
env_logger = "0.10.0"
freedesktop_entry_parser = "1.3.0"
log = "0.4.20"
pam-client = "0.5.0"
pwd = "1.4.0"
shlex = "1.2.0"
wayland-client = "0.31.1"

[dependencies.cosmic-bg-config]
git = "https://github.com/pop-os/cosmic-bg"

[dependencies.cosmic-config]
git = "https://github.com/pop-os/libcosmic"
features = ["calloop", "macro"]

[dependencies.greetd_ipc]
version = "0.9.0"
features = ["sync-codec"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
features = ["tokio", "wayland"]

[dependencies.tokio]
version = "1.33.0"
features = ["full"]
