[package]
name = "cosmic-greeter"
version = "0.1.0"
edition = "2021"

[dependencies]
greetd_ipc = "0.9"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "wayland"]

[dependencies.tokio]
version = "1"
features = ["full"]
